"""QR matrix core.

Wraps :mod:`segno` and exposes a :class:`QrMatrix` value object with a binary
numpy matrix of modules. Deliberately does **not** include quiet-zone padding
in the matrix -- the geometry layer adds any required margin based on the
physical dimensions.

The acceptance criteria for this module live in
``vbrief/active/2026-04-17-qr-matrix-core.vbrief.json`` (traces: FR-1, NFR-1).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final, Literal, get_args

import numpy as np
import numpy.typing as npt
import segno

__all__ = ["EcLevel", "QrMatrix", "build_matrix"]

#: Valid QR error-correction levels (uppercase letters).
EcLevel = Literal["L", "M", "Q", "H"]

_VALID_EC: Final[frozenset[str]] = frozenset(get_args(EcLevel))

# Boolean numpy array type for readability in annotations.
_BoolArray = npt.NDArray[np.bool_]


@dataclass(frozen=True, slots=True, eq=False)
class QrMatrix:
    """Immutable value object holding a binary QR module matrix.

    Attributes:
        modules: 2-D boolean numpy array, ``shape == (size, size)``. ``True``
            means "dark module" (print this as an extruded pixel). No quiet
            zone is included; the geometry layer is responsible for adding
            margin.
        size: Side length in modules (``== modules.shape[0]``).
        version: QR version in the range 1..40 (Micro QR is explicitly
            disabled by :func:`build_matrix`).
        ec: The effective error-correction level ("L", "M", "Q", or "H").

    Equality is intentionally not generated by the dataclass -- comparing
    numpy arrays with ``==`` yields element-wise arrays, which breaks the
    auto-generated ``__eq__``. Callers should compare ``modules`` explicitly
    via :func:`numpy.array_equal` when they need matrix equality.
    """

    modules: _BoolArray
    size: int
    version: int
    ec: EcLevel = field(default="M")


def _coerce_matrix(raw: object) -> _BoolArray:
    """Convert segno's ``tuple[bytearray, ...]`` matrix into a boolean ndarray.

    segno returns the module matrix as a tuple of ``bytearray`` rows whose
    cells are 0/1 integers. We copy into a freshly-allocated boolean array so
    the caller cannot mutate segno's internal state via the returned matrix.
    """
    arr = np.asarray(raw, dtype=np.uint8)
    if arr.ndim != 2 or arr.shape[0] != arr.shape[1]:
        raise ValueError(f"Expected a square 2-D matrix from segno, got shape={arr.shape!r}")
    return arr.astype(np.bool_, copy=True)


def build_matrix(text: str, ec: EcLevel = "M") -> QrMatrix:
    """Build a :class:`QrMatrix` from ``text`` at error-correction level ``ec``.

    Args:
        text: The payload to encode. Must be a non-empty string (URLs, plain
            text, etc.). Binary payloads are not supported in v1.
        ec: Error-correction level. One of ``"L"``, ``"M"``, ``"Q"``, ``"H"``.
            ``segno``'s ``boost_error`` behavior is disabled so the effective
            level matches the requested one exactly (deterministic NFR-1).

    Returns:
        A :class:`QrMatrix` with a boolean ``modules`` array and the QR
        version segno selected for the given payload + EC level.

    Raises:
        ValueError: If ``text`` is not a non-empty string, if ``ec`` is not a
            recognised level, or if segno returns a Micro QR / non-square
            matrix (defensive guard -- should not occur because
            ``micro=False``).
    """
    if not isinstance(text, str):
        raise ValueError(f"text must be a string, got {type(text).__name__}")
    if not text:
        raise ValueError("text must be a non-empty string")
    if ec not in _VALID_EC:
        raise ValueError(f"ec must be one of {sorted(_VALID_EC)}, got {ec!r}")

    qr = segno.make(text, error=ec.lower(), micro=False, boost_error=False)

    version_attr = qr.version
    if not isinstance(version_attr, int):
        # micro=False should prevent this; belt-and-suspenders.
        raise ValueError(f"Expected integer QR version from segno, got {version_attr!r}")

    modules = _coerce_matrix(qr.matrix)
    size = int(modules.shape[0])
    # segno normalises the error attribute to an uppercase letter.
    effective_ec = qr.error
    if effective_ec not in _VALID_EC:
        raise ValueError(f"segno returned unexpected error level {effective_ec!r}")
    # mypy sees `effective_ec: str`; the membership check above narrows it.
    return QrMatrix(
        modules=modules,
        size=size,
        version=version_attr,
        ec=effective_ec,  # type: ignore[arg-type]
    )
